# Generated by Django 5.2.3 on 2025-06-29 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customerprofile_email_customerprofile_password1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='receber_newsletter',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
