# Generated by Django 5.2.3 on 2025-06-29 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customerprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
