# Generated by Django 5.2.3 on 2025-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento no Mercado Pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preference_id',
            field=models.CharField(blank=True, help_text='ID da preferência de pagamento do Mercado Pago', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Aguardando Pagamento'), ('payment_rejected', 'Pagamento Recusado'), ('payment_approved', 'Pagamento Aprovado'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='awaiting_payment', max_length=20),
        ),
    ]
