# Generated by Django 5.2.3 on 2025-07-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_review_helpful_votes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
