# Generated by Django 5.2.3 on 2025-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_image_1_product_image_2_product_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço promocional (deixe em branco se não houver desconto)', max_digits=10, null=True),
        ),
    ]
