# Generated by Django 5.2.3 on 2025-07-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_discount_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
