# Generated by Django 5.2.3 on 2025-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nfe_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da NF-e'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfe_pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do PDF da NF-e'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfe_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da NF-e'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfe_xml_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do XML da NF-e'),
        ),
    ]
