# Generated by Django 5.2.3 on 2025-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cor_fundo',
            field=models.CharField(blank=True, help_text='Classe ou código de cor do fundo (ex: bg-primary, #000)', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='cor_texto',
            field=models.CharField(blank=True, help_text='Classe ou código de cor do texto (ex: text-white, #fff)', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='texto_botao',
            field=models.CharField(blank=True, help_text='Texto do botão (opcional)', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_botao',
            field=models.URLField(blank=True, help_text='URL do botão (opcional)'),
        ),
    ]
