# Generated by Django 5.2.3 on 2025-07-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_banner_cor_fundo_banner_cor_texto_banner_texto_botao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Peso do produto em kg para cálculo de frete', max_digits=5, verbose_name='Peso (kg)'),
        ),
    ]
