# Generated by Django 5.2.3 on 2025-07-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificacao',
            field=models.CharField(blank=True, help_text='Ex: 100% Natural, Sem Conservantes', max_length=100, null=True, verbose_name='Certificação'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes do produto', null=True, verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='product',
            name='origem',
            field=models.CharField(blank=True, help_text='Ex: Índia, Brasil, etc', max_length=100, null=True, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='product',
            name='uso',
            field=models.CharField(blank=True, help_text='Sugestão de uso do produto', max_length=200, null=True, verbose_name='Uso'),
        ),
        migrations.AddField(
            model_name='product',
            name='validade',
            field=models.CharField(blank=True, help_text='Ex: 24 meses', max_length=50, null=True, verbose_name='Validade'),
        ),
    ]
