# Generated by Django 5.2.3 on 2025-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_certificacao_product_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Altura do produto em centímetros para cálculo de frete', max_digits=5, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Comprimento do produto em centímetros para cálculo de frete', max_digits=5, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Largura do produto em centímetros para cálculo de frete', max_digits=5, verbose_name='Largura (cm)'),
        ),
    ]
