# Generated by Django 5.2.3 on 2025-07-17 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0012_review_helpful_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('email_type', models.CharField(choices=[('order_confirmation', 'Confirmação de Pedido'), ('payment_approved', 'Pagamento Aprovado'), ('payment_rejected', 'Pagamento Rejeitado'), ('order_shipped', 'Pedido Enviado'), ('order_delivered', 'Pedido Entregue'), ('order_cancelled', 'Pedido Cancelado'), ('welcome', 'Boas-vindas'), ('password_reset', 'Recuperação de Senha'), ('newsletter', 'Newsletter')], max_length=30, unique=True, verbose_name='Tipo de E-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('html_content', models.TextField(verbose_name='Conteúdo HTML')),
                ('text_content', models.TextField(blank=True, help_text='Versão em texto plano (opcional)', null=True, verbose_name='Conteúdo Texto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de E-mail',
                'verbose_name_plural': 'Templates de E-mail',
                'ordering': ['email_type'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='E-mail do Destinatário')),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Destinatário')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Contexto')),
                ('priority', models.IntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')], default=2, verbose_name='Prioridade')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Máximo de Tentativas')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Pedido')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_service.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Fila de E-mail',
                'verbose_name_plural': 'Fila de E-mails',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='E-mail do Destinatário')),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Destinatário')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('bounced', 'Retornou')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Pedido')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_service.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
