# Generated by Django 5.2.3 on 2025-07-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_publica', models.CharField(max_length=255, verbose_name='Chave Pública')),
                ('chave_privada', models.CharField(max_length=255, verbose_name='Chave Privada')),
                ('modo_sandbox', models.BooleanField(default=True, verbose_name='Modo Sandbox')),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
            },
        ),
    ]
