# Generated by Django 5.2.3 on 2025-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('novo_pedido', 'Novo Pedido'), ('pedido_pendente', 'Pedido Pendente'), ('pagamento_aprovado', 'Pagamento Aprovado'), ('pagamento_rejeitado', 'Pagamento Rejeitado'), ('acao_admin', 'Ação Administrativa')], max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
